// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;


namespace VBLauncher.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("VBLauncher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG1
        {
            get
            {
                var obj = ResourceManager.GetObject("BG1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG10
        {
            get
            {
                var obj = ResourceManager.GetObject("BG10", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG11
        {
            get
            {
                var obj = ResourceManager.GetObject("BG11", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG12
        {
            get
            {
                var obj = ResourceManager.GetObject("BG12", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG2
        {
            get
            {
                var obj = ResourceManager.GetObject("BG2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG3
        {
            get
            {
                var obj = ResourceManager.GetObject("BG3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG4
        {
            get
            {
                var obj = ResourceManager.GetObject("BG4", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG5
        {
            get
            {
                var obj = ResourceManager.GetObject("BG5", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG6
        {
            get
            {
                var obj = ResourceManager.GetObject("BG6", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG7
        {
            get
            {
                var obj = ResourceManager.GetObject("BG7", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG8
        {
            get
            {
                var obj = ResourceManager.GetObject("BG8", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap BG9
        {
            get
            {
                var obj = ResourceManager.GetObject("BG9", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap conflict_clear
        {
            get
            {
                var obj = ResourceManager.GetObject("conflict_clear", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap conflict_mixed
        {
            get
            {
                var obj = ResourceManager.GetObject("conflict_mixed", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap conflict_overwrite
        {
            get
            {
                var obj = ResourceManager.GetObject("conflict_overwrite", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap conflict_overwritten
        {
            get
            {
                var obj = ResourceManager.GetObject("conflict_overwritten", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap conflict_redundant
        {
            get
            {
                var obj = ResourceManager.GetObject("conflict_redundant", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] d3d11
        {
            get
            {
                var obj = ResourceManager.GetObject("d3d11", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] D3D8
        {
            get
            {
                var obj = ResourceManager.GetObject("D3D8", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to [Audio]
        /// CDAudio = 0
        /// DirectMusic = 0
        /// DirectShow = 0
        /// Music = 1
        /// MusicVolume = 100
        /// 
        /// [Client]
        /// debug = 17416248
        /// port = 22501
        /// rate = 0
        /// timeout = 600000
        /// 
        /// [Combat]
        /// mode = 0
        /// 
        /// [Graphics]
        /// adapter = 0
        /// clear blue = 0
        /// clear green = 0
        /// clear red = 0
        /// device = 0
        /// displaymode = 12
        /// enable bilinear filtering = 1
        /// enable lighting = 1
        /// enable startup movies = 1
        /// enable transparency = 1
        /// enable wireframe = 0
        /// fullscreen = 1
        /// height = 600
        /// mode32bpp = 0
        /// refresh = 0
        /// shadow type = 0
        /// stats = 0
        /// vsync = 0
        /// width [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default_F3
        {
            get
            {
                return ResourceManager.GetString("Default_F3", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to [Audio]
        /// GroupList = FO3.gls
        /// MusicJumpList = F3.sco
        /// 
        /// [Camera]
        /// Azimuth Speed = 360.000000
        /// Distance Max = 350.000000
        /// Distance Min = 350.000000
        /// Distance Speed = 800.000000
        /// Elevation Max = 89.000000
        /// Elevation Min = 38.500000
        /// Elevation Speed = 360.000000
        /// FOV Speed = 6.50000
        /// FOV Min = 6.00000
        /// FOV Max = 15.0000
        /// Scroll Border = 0.010000
        /// Scroll Speed = 96.000000
        /// 
        /// [Mainmenu]
        /// map name = mainmenu.map
        /// target x = 0.0
        /// target y = 5.5
        /// target z = 0.0
        /// azimuth = 0.0
        /// elevation = 0.0
        /// distance = 0
        /// fov = 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default_sys
        {
            get
            {
                return ResourceManager.GetString("Default_sys", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ;==========================================================================
        /// ; === Text based config file for dgVoodoo2
        /// ; === Use this file if you are a game modder/hacker or an experted user and
        /// ;     want to modify some advanced properties not available via the CPL.
        /// ;==========================================================================
        /// 
        /// Version                              = 0x281
        /// 
        /// ;--------------------------------------------------------------------------
        /// 
        /// [General]
        /// 
        /// ;       OutputAPI: &quot;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dgV2conf
        {
            get
            {
                return ResourceManager.GetString("dgV2conf", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dxgi
        {
            get
            {
                var obj = ResourceManager.GetObject("dxgi", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon F3
        {
            get
            {
                var obj = ResourceManager.GetObject("F3", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream f3_button_down_01
        {
            get
            {
                return ResourceManager.GetStream("f3_button_down_01", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream f3_button_up_01
        {
            get
            {
                return ResourceManager.GetStream("f3_button_up_01", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fixes
        {
            get
            {
                var obj = ResourceManager.GetObject("Fixes", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] granny2_x64
        {
            get
            {
                var obj = ResourceManager.GetObject("granny2_x64", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SUMM
        {
            get
            {
                var obj = ResourceManager.GetObject("SUMM", resourceCulture);
                return (byte[])obj;
            }
        }
    }
}