'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBLauncher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property conflict_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conflict_clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property conflict_mixed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conflict_mixed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property conflict_overwrite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conflict_overwrite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property conflict_overwritten() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conflict_overwritten", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property conflict_redundant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conflict_redundant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property d3d11() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("d3d11", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property D3D8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("D3D8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Audio]
        '''CDAudio = 0
        '''DirectMusic = 0
        '''DirectShow = 0
        '''Music = 1
        '''MusicVolume = 100
        '''
        '''[Client]
        '''debug = 17416248
        '''port = 22501
        '''rate = 0
        '''timeout = 600000
        '''
        '''[Combat]
        '''mode = 0
        '''
        '''[Graphics]
        '''adapter = 0
        '''clear blue = 0
        '''clear green = 0
        '''clear red = 0
        '''device = 0
        '''displaymode = 12
        '''enable bilinear filtering = 1
        '''enable lighting = 1
        '''enable startup movies = 1
        '''enable transparency = 1
        '''enable wireframe = 0
        '''fullscreen = 1
        '''height = 600
        '''mode32bpp = 0
        '''refresh = 0
        '''shadow type = 0
        '''stats = 0
        '''vsync = 0
        '''width [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Default_F3() As String
            Get
                Return ResourceManager.GetString("Default_F3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Audio]
        '''GroupList = FO3.gls
        '''MusicJumpList = F3.sco
        '''
        '''[Camera]
        '''Azimuth Speed = 360.000000
        '''Distance Max = 350.000000
        '''Distance Min = 350.000000
        '''Distance Speed = 800.000000
        '''Elevation Max = 89.000000
        '''Elevation Min = 38.500000
        '''Elevation Speed = 360.000000
        '''FOV Speed = 6.50000
        '''FOV Min = 6.00000
        '''FOV Max = 15.0000
        '''Scroll Border = 0.010000
        '''Scroll Speed = 96.000000
        '''
        '''[Mainmenu]
        '''map name = mainmenu.map
        '''target x = 0.0
        '''target y = 5.5
        '''target z = 0.0
        '''azimuth = 0.0
        '''elevation = 0.0
        '''distance = 0
        '''fov = 6 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Default_sys() As String
            Get
                Return ResourceManager.GetString("Default_sys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ;==========================================================================
        '''; === Text based config file for dgVoodoo2
        '''; === Use this file if you are a game modder/hacker or an experted user and
        ''';     want to modify some advanced properties not available via the CPL.
        ''';==========================================================================
        '''
        '''Version                              = 0x281
        '''
        ''';--------------------------------------------------------------------------
        '''
        '''[General]
        '''
        ''';       OutputAPI: &quot;d [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dgV2conf() As String
            Get
                Return ResourceManager.GetString("dgV2conf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dxgi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dxgi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property F3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("F3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property f3_button_down_01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("f3_button_down_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property f3_button_up_01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("f3_button_up_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Fixes() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Fixes", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SUMM() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SUMM", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
