#pragma once
#include <tchar.h>
#include <Windows.h>
#include "defs.h"
#include "memory.h"
#include "proxy.h"
#include "imguimenu.h"
#include "globals.h"
#include "functions.h"
#include "hooks.h"
#include "speed.h"
#include <filesystem>
#include "discord_register.h"
#include "discord_rpc.h"